/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./SalaryRegistry.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { SalaryRegistry } from "~~/contracts/SalaryRegistry";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { SalaryRegistry as SalaryRegistry_LOCAL } from "./SalaryRegistry.local";

const REMOTE = {
  11155111: {
    address: "0x14bA1954AE0a15e65b0B3405F3849f18DD5366eB",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "admin",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedSalary",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "grantManagerAccess",
        inputs: [
          {
            name: "manager",
            type: "address",
            internalType: "address",
          },
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "grantObserverAccess",
        inputs: [
          {
            name: "observer",
            type: "address",
            internalType: "address",
          },
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "hasSalary",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "register",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "roles",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint8",
            internalType: "enum SalaryRegistry.Role",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "setRole",
        inputs: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
          {
            name: "role",
            type: "uint8",
            internalType: "enum SalaryRegistry.Role",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setSalary",
        inputs: [
          {
            name: "employee",
            type: "address",
            internalType: "address",
          },
          {
            name: "encSalary",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "ObserverAccessGranted",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "observer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Registered",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "RoleGranted",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "role",
            type: "uint8",
            indexed: false,
            internalType: "enum SalaryRegistry.Role",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SalarySet",
        inputs: [
          {
            name: "employee",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "handle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10817378,
  },
} as const;

export const SalaryRegistry = {
  ...REMOTE,
  ...SalaryRegistry_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
